namespace WarframeApiWrapper
{
    public enum MissionType
    {
        Defense,
        MobileDefense,
        Survival,
        Extermination,
        Disruption,
        Excavation,
        Spy,
        Interception,
        Sabotage,
        Rescue,
        Capture,
        Alchemy,
        VoidFlood,
        VoidCascade,
        VoidArmagedon,
        Assassination,
        Corruption,
        Orphix,
        Skirmish,
        Volatile,
        Assault,
        FreeRoam,
        Unknown,
    }
}
